/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OralCareRouteImport } from './routes/oral-care'
import { Route as HealthcareRouteImport } from './routes/healthcare'
import { Route as CosmeticsRouteImport } from './routes/cosmetics'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OralCareRoute = OralCareRouteImport.update({
  id: '/oral-care',
  path: '/oral-care',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcareRoute = HealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticsRoute = CosmeticsRouteImport.update({
  id: '/cosmetics',
  path: '/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cosmetics': typeof CosmeticsRoute
  '/healthcare': typeof HealthcareRoute
  '/oral-care': typeof OralCareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cosmetics': typeof CosmeticsRoute
  '/healthcare': typeof HealthcareRoute
  '/oral-care': typeof OralCareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cosmetics': typeof CosmeticsRoute
  '/healthcare': typeof HealthcareRoute
  '/oral-care': typeof OralCareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cosmetics' | '/healthcare' | '/oral-care' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cosmetics' | '/healthcare' | '/oral-care' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/cosmetics'
    | '/healthcare'
    | '/oral-care'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CosmeticsRoute: typeof CosmeticsRoute
  HealthcareRoute: typeof HealthcareRoute
  OralCareRoute: typeof OralCareRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oral-care': {
      id: '/oral-care'
      path: '/oral-care'
      fullPath: '/oral-care'
      preLoaderRoute: typeof OralCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare': {
      id: '/healthcare'
      path: '/healthcare'
      fullPath: '/healthcare'
      preLoaderRoute: typeof HealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetics': {
      id: '/cosmetics'
      path: '/cosmetics'
      fullPath: '/cosmetics'
      preLoaderRoute: typeof CosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CosmeticsRoute: CosmeticsRoute,
  HealthcareRoute: HealthcareRoute,
  OralCareRoute: OralCareRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
